language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: nightly
  fast_finish: true

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install codacy-coverage

script:
  - coverage run -m pytest

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
